# Generated by Django 4.2.21 on 2026-01-23 00:55

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("pontos_totais", models.PositiveIntegerField(default=0)),
                (
                    "membros",
                    models.ManyToManyField(
                        related_name="grupos", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Missao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150, verbose_name="Título")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("diaria", "Diária"),
                            ("semanal", "Semanal"),
                            ("especial", "Especial"),
                            ("meta", "Meta de Cadastro"),
                            ("evento", "Evento/Temática"),
                            ("colaborativa", "Colaborativa"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "pontos",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Pontos por completar esta missão",
                        verbose_name="Pontos",
                    ),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "meta",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        help_text="Quantidade necessária para completar (ex: 10 cadastros)",
                        null=True,
                        verbose_name="Meta",
                    ),
                ),
                (
                    "secreta",
                    models.BooleanField(default=False, verbose_name="Missão Secreta"),
                ),
                (
                    "data_inicio",
                    models.DateField(blank=True, null=True, verbose_name="Início"),
                ),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Término"),
                ),
                (
                    "destaque",
                    models.BooleanField(
                        default=False, verbose_name="Missão em Destaque"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "criador",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário que criou a missão (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="missoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Missão",
                "verbose_name_plural": "Missões",
                "ordering": ["-data_inicio", "-data_criacao", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="Nivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(unique=True)),
                ("nome", models.CharField(max_length=100)),
                ("pontos_minimos", models.PositiveIntegerField()),
                ("pontos_maximos", models.PositiveIntegerField()),
                ("beneficios", models.TextField(blank=True)),
                ("surpresa_oculta", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="PlantaReferencial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_popular",
                    models.CharField(max_length=200, verbose_name="Nome popular"),
                ),
                (
                    "nome_cientifico",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome científico"
                    ),
                ),
                (
                    "parte_comestivel",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Parte comestível"
                    ),
                ),
                (
                    "forma_uso",
                    models.TextField(blank=True, verbose_name="Forma de uso"),
                ),
                (
                    "grupo_taxonomico",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Grupo taxonômico",
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Origem"
                    ),
                ),
                (
                    "bioma",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Bioma"
                    ),
                ),
                (
                    "regiao_ocorrencia",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Região de ocorrência",
                    ),
                ),
                (
                    "fonte",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Fonte"
                    ),
                ),
                (
                    "nome_cientifico_valido",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nome científico válido",
                    ),
                ),
                (
                    "nome_cientifico_corrigido",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nome científico corrigido",
                    ),
                ),
                (
                    "fonte_validacao",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Fonte de validação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planta referencial",
                "verbose_name_plural": "Plantas referenciais",
                "ordering": ["nome_popular"],
            },
        ),
        migrations.CreateModel(
            name="SugestaoMissao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("descricao", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("aprovado", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RankingRevisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pontuacao", models.PositiveIntegerField(default=0)),
                ("avaliacoes", models.PositiveIntegerField(default=0)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-pontuacao"],
            },
        ),
        migrations.CreateModel(
            name="PontuacaoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pontos", models.IntegerField(default=0)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "nivel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mapping.nivel",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pontuacao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PontoPANC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_popular",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Nome popular"
                    ),
                ),
                (
                    "tipo_local",
                    models.CharField(
                        choices=[
                            ("quintal", "Quintal"),
                            ("reserva", "Reserva"),
                            ("rua", "Beira de rua"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=20,
                        verbose_name="Tipo de local",
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Endereço"
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Número"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Bairro"
                    ),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=255, verbose_name="Cidade"),
                ),
                (
                    "estado",
                    models.CharField(blank=True, max_length=255, verbose_name="Estado"),
                ),
                (
                    "colaborador",
                    models.CharField(
                        blank=True,
                        help_text="Nome ou apelido de quem cadastrou",
                        max_length=255,
                        verbose_name="Colaborador",
                    ),
                ),
                (
                    "relato",
                    models.TextField(
                        blank=True,
                        help_text="História, observação ou uso do local",
                        verbose_name="Relato",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos/", verbose_name="Foto"
                    ),
                ),
                (
                    "localizacao",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326, verbose_name="Localização"
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "nome_popular_sugerido",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome popular sugerido (IA)",
                    ),
                ),
                (
                    "nome_cientifico_sugerido",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nome científico sugerido (IA)",
                    ),
                ),
                (
                    "score_identificacao",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Confiança da identificação automática (%)",
                    ),
                ),
                (
                    "status_identificacao",
                    models.CharField(
                        choices=[
                            ("confirmado", "Confirmado"),
                            ("sugerido", "Sugerido pela IA"),
                            ("pendente", "Aguardando revisão"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status da identificação",
                    ),
                ),
                (
                    "status_validacao",
                    models.CharField(
                        choices=[
                            ("pendente", "Em validação"),
                            ("aprovado", "Aprovado"),
                            ("reprovado", "Reprovado"),
                            ("pendencia", "Pendência do usuário"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status de validação",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pontos_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário que cadastrou",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pontos",
                        to="mapping.grupo",
                        verbose_name="Grupo/Comunidade",
                    ),
                ),
                (
                    "planta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mapping.plantareferencial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ponto de PANC",
                "verbose_name_plural": "Pontos de PANC",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ParecerValidacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parecer",
                    models.CharField(
                        choices=[
                            ("aprovado", "Aprovado"),
                            ("reprovado", "Reprovado"),
                            ("pendencia", "Pendência"),
                        ],
                        max_length=10,
                    ),
                ),
                ("comentario", models.TextField(blank=True)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "especialista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ponto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pareceres",
                        to="mapping.pontopanc",
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="MissaoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=0)),
                ("progresso", models.PositiveIntegerField(default=0)),
                ("completada", models.BooleanField(default=False)),
                ("data_conclusao", models.DateTimeField(blank=True, null=True)),
                (
                    "missao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mapping.missao"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricoGamificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acao", models.CharField(max_length=150)),
                ("pontos", models.IntegerField(default=0)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="ID de referência, missão, badge, ponto, evento etc.",
                        max_length=150,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_gamificacao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensagem", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "ponto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="mapping.pontopanc",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField(blank=True, null=True)),
                ("pontos", models.PositiveIntegerField(default=20)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participantes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="eventos_participados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BotaoFlutuante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exibido", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "icone",
                    models.ImageField(
                        blank=True, null=True, upload_to="badges/", verbose_name="Ícone"
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "nivel",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Nível ou raridade do badge (1=comum, 2=raro, etc)",
                    ),
                ),
                (
                    "unico",
                    models.BooleanField(
                        default=False,
                        help_text="É um badge único para o primeiro a conquistar?",
                    ),
                ),
                (
                    "missao",
                    models.ForeignKey(
                        blank=True,
                        help_text="Missão relacionada (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mapping.missao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Badge / Insígnia",
                "verbose_name_plural": "Badges / Insígnias",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="AlertaClimatico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        help_text="Tipo do alerta (ex: Queimada, Enchente, Chuva Intensa, Calor Extremo)",
                        max_length=100,
                        verbose_name="Tipo de alerta",
                    ),
                ),
                (
                    "severidade",
                    models.CharField(
                        blank=True,
                        help_text="Nível de severidade do alerta (ex: Moderado, Alto, Perigo, Observação)",
                        max_length=50,
                        null=True,
                        verbose_name="Severidade",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do alerta e dos impactos esperados",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "inicio",
                    models.DateTimeField(
                        help_text="Data e hora de início da vigência do alerta",
                        verbose_name="Início",
                    ),
                ),
                (
                    "fim",
                    models.DateTimeField(
                        help_text="Data e hora do fim da vigência do alerta",
                        verbose_name="Fim",
                    ),
                ),
                (
                    "municipio",
                    models.CharField(
                        blank=True,
                        help_text="Município relacionado ao alerta",
                        max_length=100,
                        null=True,
                        verbose_name="Município",
                    ),
                ),
                (
                    "uf",
                    models.CharField(
                        blank=True,
                        help_text="UF (estado) relacionado ao alerta",
                        max_length=2,
                        null=True,
                        verbose_name="UF",
                    ),
                ),
                (
                    "id_alerta",
                    models.CharField(
                        blank=True,
                        help_text="Identificador único do alerta na fonte original",
                        max_length=100,
                        null=True,
                        verbose_name="ID do Alerta na fonte",
                    ),
                ),
                (
                    "fonte",
                    models.CharField(
                        default="INMET",
                        help_text="Fonte do alerta (ex: INMET, CEMADEN, Open-Meteo, Manual)",
                        max_length=50,
                        verbose_name="Fonte",
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="URL do ícone ilustrativo do tipo de alerta",
                        max_length=255,
                        null=True,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data de registro do alerta no sistema",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "ponto",
                    models.ForeignKey(
                        help_text="Ponto PANC associado ao alerta",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="mapping.pontopanc",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta Climático",
                "verbose_name_plural": "Alertas Climáticos",
                "ordering": ["-inicio"],
            },
        ),
        migrations.CreateModel(
            name="UsuarioBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_conquista", models.DateTimeField(auto_now_add=True)),
                (
                    "contexto",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Missão/Evento relacionado à conquista",
                        max_length=200,
                    ),
                ),
                (
                    "nivel_usuario",
                    models.PositiveIntegerField(
                        default=1, help_text="Nível do usuário no momento da conquista"
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_badges",
                        to="mapping.badge",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conquista de Badge",
                "verbose_name_plural": "Conquistas de Badge",
                "ordering": ["-data_conquista"],
                "unique_together": {("usuario", "badge")},
            },
        ),
        migrations.AddIndex(
            model_name="pontopanc",
            index=models.Index(
                fields=["cidade", "estado"], name="mapping_pon_cidade_319702_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pontopanc",
            index=models.Index(
                fields=["tipo_local"], name="mapping_pon_tipo_lo_c5143c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pontopanc",
            index=models.Index(
                fields=["criado_em"], name="mapping_pon_criado__653f7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pontopanc",
            index=models.Index(fields=["grupo"], name="mapping_pon_grupo_i_db1d66_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="parecervalidacao",
            unique_together={("ponto", "especialista")},
        ),
        migrations.AlterUniqueTogether(
            name="missaousuario",
            unique_together={("missao", "usuario")},
        ),
        migrations.AlterUniqueTogether(
            name="alertaclimatico",
            unique_together={("ponto", "tipo", "inicio", "fim")},
        ),
    ]
